services:
 facefusion-rocm:
  build:
   context: .
   dockerfile: Dockerfile.rocm
  command: [ 'python', 'facefusion.py', 'run', '--execution-providers', 'rocm' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  ports:
  - 7880:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: rocm
       count: all
       capabilities: [ gpu, video ]