services:
 facefusion-tensorrt:
  build:
   context: .
   dockerfile: Dockerfile.tensorrt
  command: [ 'python', 'facefusion.py', 'run', '--execution-providers', 'tensorrt' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  ports:
  - 7875:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       count: all
       capabilities: [ gpu, video ]